### ISSUE TITLE
error during setup

### ISSUE THREAD

**Issue by stenbosch** [dontinelli/fyta_cli#7]
When I start the integration process, the following error message appears after the update (in the previous version, the config_flow.py ran fine.)
<img width="546" alt="Bildschirmfoto 2024-02-17 um 12 48 52" src="https://github.com/dontinelli/fyta_cli/assets/24548965/8e36ae1a-fcd4-47ef-bf06-c13e60f6dbd7">

In the previous version, the devices were created cleanly, but no data arrived. I also started writing an integration, but without authentication with user/password. but with bearer token. Data is already arriving there. I couldn't manage to authenticate and renew the token

**Comment by dontinelli** [comment]
What was the mistake and how could it be resolved?
